#0xProto Nerd Font Mono:style=Bold
#0xProto Nerd Font Mono:style=Regular

[font]
size = 12.0

[font.bold]
family = "0xProto Nerd Font Mono"
style = "Bold"

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

